# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78ad6495a26da4d22b6bb55b9217fff02d3fd150c6033e3fe236aa6b56cd78621f615b63ea0cce44d117d96cc5c7d4c263715bd947b070966bc9fa75f4e43ef3

test:
  secret_key_base: 72e517dc03880aa136bbb0bea94105dea377cd5da92a59705ca9ee9aa2c2c72cc651748539818a180e69a36bd72173ef6ce266fef9bbc02dcca361a7aa6066f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
